[tool.poetry]
name = "tidyframe"
version = "0.1.0"
description = "Tidy interface to polars"
authors = ["Mark Fairbanks"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
